### ISSUE TITLE
Use reflet mongoose with plugins

### ISSUE THREAD

**Issue by paul-hristea** [jeremyben/reflet#4]
Hello!

I'm wondering if reflet mongoose can be used with plugins?
I'm trying to implement soft delete feature, as described in this stackoverflow post: https://stackoverflow.com/a/62004999
Is there another recommended way to implement soft delete with reflet mongoose, or is there a way to use this kind of plugins with the library?

Thanks!

**Comment by jeremyben** [comment]
Sure you can do everything that you used to do with plain mongoose, including plugins, as Reflet is a thin wrapper of decorators.

## global plugin

If you want your plugin to be global, simply follow the mongoose doc: https://mongoosejs.com/docs/plugins.html#global

```ts
mongoose.plugin(softDeletePlugin)
```

Then you can augment the global Document interface this way (since **v1.4.0**):

```ts
declare global { // use `declare global` if you are in a module file (with export/import)
  namespace RefletMongoose {
    interface Document {
      isDeleted: boolean;
      deletedAt: Date | null;
    }
  }
}
```

## schema plugin

If your want your plugin to be applied to specific models, here is the way:

```ts
@Model()
@SchemaCallback((schema) => schema.plugin(softDeletePlugin))
export class User extends Model.I {
  // no need to decorate
  isDeleted: boolean; 
  deletedAt: Date | null;
}
```

**Comment by paul-hristea** [comment]
I ended up using the @SchemaCallback annotation.

Thanks a lot!
